### ISSUE TITLE
R the models in the canonical object space?

### ISSUE THREAD

**Issue by Jianghanxiao** [UT-Austin-RPL/Ditto#9]
Hi,

I notice that in the demo, the laptop is converted from depth image to camera coordinate, then to world coordinate. What's the reason to convert into the world coordinate? Does it promise that the object is in the canonical object space?

When training on the shape2motion data, is the training data in the canonical object space (with a canonical pose)? Or it's just in the camera coordinate

**Comment by Jianghanxiao** [comment]
Or it's just to fuse several depth images, then to convert it into the world coordinate? In the world coordinate, does the objects always have consistent up direction? Or the objects always have canonical pose? I care about the case in the training data

Thanks a lot for your great work and code

**Comment by Steve-Tod** [comment]
Hi, that's a great question. During the training, we only randomly rotate the object across the z-axis because of the following considerations:

1. In the real world, most daily objects are upright or easy to be upright.
2. Keeping objects upright can ensure a consistent axis direction notation.
3. Training is more stable, and the performance is better.

We also tried randomly rotating the object in the SO(3) space and allowing [ambiguity](https://github.com/UT-Austin-RPL/Ditto/blob/c9bd94ede2aa4343f59f52bc1e3b1e3eccd96484/src/models/modules/losses_dense_joint.py#L63) in axis direction in prediction, it kinda works but not as good as we put the object upright.

**Comment by Jianghanxiao** [comment]
Thanks for the clear reply!!
